# Site settings
title: P19 - a nineteenth-century literature and culture seminar 
email: philadelphia dot nineteen at gmail dot com
description: > # this means to ignore newlines until "baseurl:"
  A cross-institutional, interdisciplinary, nineteenth-century literature and culture seminar in Philadelphia.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: philadelphia19
github_username:  p19

# Build settings
markdown: kramdown
